# Generated by Django 6.0.3 on 2026-03-23 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Monster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('NECROPHAGE', 'Necrophage'), ('RELICT', 'Relict'), ('HYBRID', 'Hybrid'), ('SPECTER', 'Specter')], max_length=20)),
                ('description', models.TextField()),
                ('weakness', models.CharField(max_length=255)),
                ('danger_level', models.IntegerField(default=1)),
            ],
        ),
    ]
