# Generated by Django 6.0.3 on 2026-03-24 13:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bestiary', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monster',
            name='weakness',
        ),
        migrations.AddField(
            model_name='monster',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='monster',
            name='oil_type',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='monster',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, unique=True),
        ),
        migrations.AddField(
            model_name='monster',
            name='weakness_sign',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='monster',
            name='category',
            field=models.CharField(choices=[('NECROPHAGE', 'Necrophage'), ('RELICT', 'Relict'), ('HYBRID', 'Hybrid'), ('SPECTER', 'Specter'), ('CURSED', 'Cursed One'), ('DRACONID', 'Draconid')], max_length=20),
        ),
        migrations.AlterField(
            model_name='monster',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
